@host = http://localhost:5031

### Search bus stations
GET {{host}}/api/BusStation/Search?keyword=&page=1&pageSize=10
Accept: application/json

### Get bus station by id
GET {{host}}/api/BusStation/Get/1
Accept: application/json

### Create bus station
POST {{host}}/api/BusStation/Create
Content-Type: application/json

{
  "name": "Tram Don Quan 1",
  "address": "123 Nguyen Hue, Quan 1",
  "description": "Tram don hoc sinh buoi sang",
  "latitude": 10.7769,
  "longitude": 106.7009,
  "isEnabled": true
}

### Update bus station
PUT {{host}}/api/BusStation/Update/1
Content-Type: application/json

{
  "name": "Tram Don Quan 1 - Cap Nhat",
  "address": "125 Nguyen Hue, Quan 1",
  "description": "Tram don hoc sinh da cap nhat",
  "latitude": 10.7775,
  "longitude": 106.7015,
  "isEnabled": true
}

### Delete bus station
DELETE {{host}}/api/BusStation/Delete/1
Accept: application/json
