@host = http://localhost:5031

### Create driver
POST {{host}}/api/User/CreateDriver
Content-Type: application/json

< ./create_driver_sample.json

### Get user
GET {{host}}/api/User/Get/1

### Search driver
GET {{host}}/api/User/Search?role=driver&page=1&pageSize=10
