@host = http://localhost:5031

### Search attendance
GET {{host}}/api/Attendance/Search?page=1&pageSize=10&date=2026-03-25
Accept: application/json

### Get attendance by id
GET {{host}}/api/Attendance/Get/1
Accept: application/json

### Manual check in at selected station
POST {{host}}/api/Attendance/ManualCheckIn
Content-Type: application/json

{
  "studentId": 2,
  "busId": 1,
  "stationId": 1,
  "date": "2026-03-25T00:00:00",
  "time": "07:05:00"
}

### Manual check out at correct station
POST {{host}}/api/Attendance/ManualCheckOut
Content-Type: application/json

{
  "studentId": 2,
  "busId": 1,
  "stationId": 2,
  "date": "2026-03-25T00:00:00",
  "time": "16:35:00"
}

### Manual check out at wrong station to trigger guardian warning
### Use this request instead of the correct check out request above
POST {{host}}/api/Attendance/ManualCheckOut
Content-Type: application/json

{
  "studentId": 2,
  "busId": 1,
  "stationId": 3,
  "date": "2026-03-25T00:00:00",
  "time": "16:40:00"
}
